version: "3.9"
services:
  web:
    container_name: manniwatch_web_server
    image: manniwatch/test
    build: .
    stop_signal: SIGINT
    init: true
    ports:
      - "4200:3000"
    environment:
      NODE_ENV: production
      MW_ENDPOINT: https://kvg-kiel.de
